### ISSUE TITLE
Add device detection

### ISSUE THREAD

**Issue by apearson** [apearson/node-red-contrib-insteon#3]
https://www.npmjs.com/package/usb-detection

**Comment by apearson** [comment]
Putting this on hold because this library locks up node-red

**Comment by PaulWieland** [comment]
I don’t think it’s that necessary either. Maybe just some simple instructions for people on how to find their device in `/dev`. 

The permissions are the worst part, especially when using docker.

**Comment by apearson** [comment]
What I was going for was a better way to detect when a USB Device was plugged and unplugged instead of setting a timeout.  The more I think about it the more I don't like having an extra native dependence
